### ISSUE TITLE
Rendered without styles

### ISSUE THREAD

**Issue by bhelx** [Nola-Devs/Nola-Dev-Site#34]
When you load the page it renders without the CSS applied. It also seems to take 3 to 4 seconds. I think it's because it's waiting on the CSS to come down, but I'm not sure how to fix this because next.js seems to be rendering all this stuff and I'm not familiar with it. It's unclear what `data-precedence="next"` means on the `<link>` element. After the first page loads the result, it is cached so it's faster but it still renders before the css loads resulting in a jarring experience.

<img width="738" alt="Screenshot 2023-07-16 at 11 56 43 AM" src="https://github.com/Nola-Devs/Nola-Dev-Site/assets/185919/cbd62ae1-96e7-4386-b3f9-22c9d063cfdf">

<img width="1240" alt="Screenshot 2023-07-16 at 11 45 02 AM" src="https://github.com/Nola-Devs/Nola-Dev-Site/assets/185919/22e43af3-1122-43dc-b02e-3cc005838050">

**Comment by colinwilliams91** [comment]
Will look into [generateStaticParams](https://nextjs.org/docs/app/api-reference/functions/generate-static-params) from Next Docs per @Aeshus as solution.

**Comment by codingMustache** [comment]
This should be fixed now
