### ISSUE TITLE
fix: discord invite is invalid

### ISSUE THREAD

**Issue by EtanHey** [Nola-Devs/Nola-Dev-Site#36]
Discord invite link shown at the readme is invalid,
can't find the link anywhere so can't fix and make a pull request.

**Comment by Aeshus** [comment]
Not this again...
Here's a temporary invite (30d) [https://discord.gg/HDVhWrZ3v](https://discord.gg/HDVhWrZ3v)

**Comment by colinwilliams91** [comment]
Yeah, not sure how we can get a persistent link. For now I updated temp link again today.

**Comment by Aeshus** [comment]
Here's a new permanent link: [https://discord.gg/bvrS72gaKS](https://discord.gg/bvrS72gaKS)
