### ISSUE TITLE
feat: Replace Google Form to add Events

### ISSUE THREAD

**Issue by colinwilliams91** [Nola-Devs/Nola-Dev-Site#86]
The user submitted event forms (currently Google Forms) should send a notification to the Nola Devs Discord upon user submission. Where any contributor can validate the event submission. (human validation)

### MVP
The current workflow is: 
Google Form --> Google Sheet
--> from the Google Sheet data should be parsed and submitted as a Calendar Event to a generic Calendar ("one-offs Cal")

### Post MVP
This should eventually not be an embedded `<iframe>` and should be a custom front end component form to capture required fields, filter profanity/racism/sexism/homophobia etc, and enforce user submission limits.

[npm bad words](https://www.npmjs.com/package/bad-words)

**Comment by codingMustache** [comment]
Reference for possible keys and Formatting:
https://birdie0.github.io/discord-webhooks-guide/index.html

**Comment by codingMustache** [comment]
Form will need fields
- [ ] Email
- [ ] Name
- [ ] Org
- [ ] Event name
- [ ] Description
- [ ] Location
- [ ] Date
- [ ] Time start/end
- [ ] Link to Event Page

**Comment by codingMustache** [comment]
Create channel in Nola Dev Discord for Webhooks to be sent to
