### ISSUE TITLE
Weekly Event Display

### ISSUE THREAD

**Issue by Aeshus** [Nola-Devs/Nola-Dev-Site#95]
# Weekly Event Display

## Description:
The idea is to display the events from the calendar, containing only the ones in the current week. Thus, a visitor can quickly see that there's a Hacknight this week or a Front End Party event this week.

This should go well with the new event form. All one would need to do to get an event added to the website would be to add an event on the Google Calendars tracked by this component.

## High Level Architecture:

```mermaid
sequenceDiagram
    participant User
    participant Website
    participant Calendar
    
    User->>Website: Navigates to week event component
    
    Website->>Calendar: Requests list of all events
    Calendar-->>Website: All events for all days
    Website->>Website: Prune and format data
    
    Website-->>User: All events in week
    Note left of Website: This is formatted as the `Event` interface
    
    User->>User: render events
```

(Always wanted to test out that feature ;) )

Note that the diagram does not show the codepath for the development environment. In the development environment, it just reads some pre-collected event JSON.

---

A new secret key will be required for this component to access Google's APIs. I've been having trouble setting one up, but I can still query and access calendar just fine through the Google API Explorer interface (I just can't query it through code).

---

This is all of the data we extract from the fields provided to us by [Google's Calendar API](https://developers.google.com/calendar/api/v3/reference/events#resource-representations).

We're specifically using the `https://www.googleapis.com/calendar/v3/calendars/calendarId/events` API Endpoint (which means we have to iterate and merge multiple calendar IDs as it only takes reads at a time)

```json5
{
  // [...]
  "items": [ // Event
    {
      // [...]
      "htmlLink": string,
      // [...]
      "summary": string,
      "description": string,
      "location": string,
      // [...]
      "start": {
        // [...]
        "dateTime": datetime,
        // [...]
      },
      "end": {
        // [...]
        "dateTime": datetime,
        // [...]
      },
    }
  ]
}
```

Which becomes this interface:
```ts
export interface Event {
  htmlLink: string;
  summary: string;
  description: string;
  location: string;
  orgEmoji: string;
  start: {
    dateTime: string;
  };
  end: {
    dateTime: string;
  };
}
```

Luckily for us, Google's API isn't that complicated to use. The API provides the ability to filter events by a start and end date, which makes it so we don't need to deal with filtering out those events ourselves.

**Comment by colinwilliams91** [comment]
great, thorough issue. im going to close [issue 75](https://github.com/Nola-Devs/Nola-Dev-Site/issues/75) and
